/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PartB;
import PartA.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;

import PartA.Module;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;

public class App {
    public static void main(String[] args) {


        Student s1 = new Student("Evan Fahy", 21, "27/11/1999", 18391616);
        Student s2 = new Student("Gregg Heffley", 22, "09/01/1999", 17163212);
        Student s3 = new Student("Sarah Johnson", 23, "24/07/1998", 12184565);
        Student s4 = new Student("Jeremy Mortimer", 19, "05/12/2001", 19364356);
        Student s5 = new Student("Gordon Ramsey", 21, "18/04/1999", 18673423);

        ArrayList<Student> students = new ArrayList<>(Arrays.asList(s1, s2, s3, s4, s5));

        String formatter = "yyyy-dd-MM hh:mm:ss";
        Course course1 = new Course("CS&IT", DateTime.parse("2021-01-01 12:59:59", DateTimeFormat.forPattern(formatter)), DateTime.parse("2022-01-01 12:59:59", DateTimeFormat.forPattern(formatter)));

        Course course2 = new Course("Env Science", DateTime.parse("2021-01-01 12:59:59", DateTimeFormat.forPattern(formatter)), DateTime.parse("2022-01-01 12:59:59", DateTimeFormat.forPattern(formatter)));

        PartA.Module module1 = new PartA.Module("Software Engineering", "CT417");
        PartA.Module module2 = new PartA.Module("Real Time Systems", "CT420");
        PartA.Module module3 = new PartA.Module("Information Retrieval", "CT4100");
        PartA.Module module4 = new PartA.Module("Machine Learning", "CT4101");

        // Students added to modules
        module1.setStudents(new ArrayList<Student>(Arrays.asList(s1, s3)));
        module2.setStudents(new ArrayList<Student>(Arrays.asList(s1, s2, s4)));
        module3.setStudents(new ArrayList<Student>(Arrays.asList(s1, s4)));
        module4.setStudents(new ArrayList<Student>(Arrays.asList(s2, s4, s5)));

        s1.setModules(new ArrayList<Module>(Arrays.asList(module1, module2, module3)));
        s2.setModules(new ArrayList<Module>(Arrays.asList(module2, module4)));
        s3.setModules(new ArrayList<Module>(Collections.singletonList(module1)));
        s4.setModules(new ArrayList<Module>(Arrays.asList(module2, module3, module4)));
        s5.setModules(new ArrayList<Module>(Collections.singletonList(module4)));

        // modules added to courses
        course1.setModules(new ArrayList<PartA.Module>(Arrays.asList(module1, module2, module3)));
        course2.setModules(new ArrayList<PartA.Module>(Arrays.asList(module3, module4)));

        // Students added to courses
        course1.setStudents(new ArrayList<Student>(Arrays.asList(s1, s3)));
        course2.setStudents(new ArrayList<Student>(Arrays.asList(s2, s4, s5)));

        s1.setCourses(new ArrayList<Course>(Collections.singletonList(course1)));
        s2.setCourses(new ArrayList<Course>(Collections.singletonList(course2)));
        s3.setCourses(new ArrayList<Course>(Collections.singletonList(course1)));
        s4.setCourses(new ArrayList<Course>(Collections.singletonList(course2)));
        s5.setCourses(new ArrayList<Course>(Collections.singletonList(course2)));

        System.out.println(course1);
        System.out.println(course2);

        for(Student student : students) {
            System.out.println(student);
        }
        
    }
}
